### ISSUE TITLE
Patch __SmartDisplay__/graphics/empty.png does not match any enabled mod

### ISSUE THREAD

**Issue by an256** [petrukhnov/FactorioSmartDisplay#1]
Запускал из папки.
Версии 0.15,10 и 0,15.15 та же ошибка при загрузке.

На сайте 1.1.1 версия а тут 1.1.0

**Comment by petrukhnov** [comment]
Да 1.1.0 не работает корректно с 0.15
Залил сюда 1.1.1
Обновили совместимость до 0.16
